// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyGOH6fcD6GWWyBfrpMFHVGy81evPkJjQ',
    appId: '1:854215819470:web:ac84ece0fdbb2ebf6ad09f',
    messagingSenderId: '854215819470',
    projectId: 'message-app-cf4b2',
    authDomain: 'message-app-cf4b2.firebaseapp.com',
    storageBucket: 'message-app-cf4b2.appspot.com',
    measurementId: 'G-D5QMXP5L9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqhen16DhwYovZP5OwPKmaSwvf6fSCA4w',
    appId: '1:854215819470:android:9e7ebdcbc0b67f0e6ad09f',
    messagingSenderId: '854215819470',
    projectId: 'message-app-cf4b2',
    storageBucket: 'message-app-cf4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdvEAMTodCE4VwA7lJskBnv0-SXAX-bEU',
    appId: '1:854215819470:ios:e7dcf6569114b5906ad09f',
    messagingSenderId: '854215819470',
    projectId: 'message-app-cf4b2',
    storageBucket: 'message-app-cf4b2.appspot.com',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdvEAMTodCE4VwA7lJskBnv0-SXAX-bEU',
    appId: '1:854215819470:ios:86683ab1d3bedc246ad09f',
    messagingSenderId: '854215819470',
    projectId: 'message-app-cf4b2',
    storageBucket: 'message-app-cf4b2.appspot.com',
    iosBundleId: 'com.example.hw4.RunnerTests',
  );
}
